[package]
name = "simpletodo"
version = "0.1.0"
edition = "2018"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
# gtk = { version = "0.3", package = "gtk4" }
gtk = { git = "https://github.com/gtk-rs/gtk4-rs.git", package = "gtk4" }
once_cell = "1.9.0"
